sudo : required
language: generic

services:
  - docker
  
before_install:
  - docker build -f Dockerfile.dev -t aseadadocker:docker-react .

script:
  - docker run -e CI=true aseadadocker:docker-react npm run test 